#! /bin/sh

sxhkd &

# source the colors
. "${HOME}/.cache/wal/colors.sh"

# set the border colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc monitor DP3 -d I II III IV V
bspc monitor HDMI2 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium 
bspc rule -a smplayer desktop='^1'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mednafen desktop='^6' border=off
bspc rule -a whatsapp-nativefier-d52542 desktop='^2'
